### ISSUE TITLE
Default value for std::string

### ISSUE THREAD

**Issue by lsioctl** [mcmtroffaes/inipp#13] opened 2021-02-12 17:18 UTC
Hello,

First of all, thank you for inipp, it is very lightweight and I think, very elegant.

I have an issue when trying to simulate 'default values' for std::string.

For example, if I insert those lines in example.cpp, with the same example.ini,
where Usera is not defined :

```
std::string user = "testUser";
inipp::extract(ini.sections["bitbucket.org"]["Usera"], user);
std::cout << "bitbucket.org user: " << user << std::endl;
```
the output contains:
```
bitbucket.org user:
```
instead of what I would have expected:
```
bitbucket.org user: testUser
```

While looking why in the source code I found that my test uses this template specialization:

```
template <typename CharT>
inline bool extract(const std::basic_string<CharT> & value, std::basic_string<CharT> & dst) {
	dst = value;
	return true;
}
```
So it is clear why my default string became an empty string.

Would it be possible to have the same feature as integer or boolean ? 
- return false if no match
- not changing the existing value

Please tell me if I could help.

Thank you.

**Comment by mcmtroffaes** [comment] 2021-02-12 22:49
Thanks for your kind words about the code.

The problem is that, in your scenario,

```cpp
ini.sections["bitbucket.org"]["Usera"]
```

creates a new entry "Usera" in the "bitbucket.org" section using the default string constructor, thus resulting in an empty string, which then gets passed to the user variable. To handle missing entries and custom default values, you could use something like this: https://stackoverflow.com/a/2333816 I don't think you need the extract function in your example, as that's purely for convenient conversion from strings to other types.

Does this explain, and help you further?

**Comment by mcmtroffaes** [comment] 2021-02-13 17:53
What do you think of this (just committed)?

```cpp
template <typename CharT, typename T>
inline bool get_value(const std::map<std::basic_string<CharT>, std::basic_string<CharT>> & sec, const std::basic_string<CharT> & key, T & dst) {
	const auto it = sec.find(key);
	if (it == sec.end()) return false;
	return extract(it->second, dst);
}
```

I think that function has the behaviour you wish. Example:

```cpp
int a = 4;
get_value(sec, std::string("a"), a);
```

Here, ``a`` will retain the value 4 if the key does not exist in the section ``sec``, or if the value cannot be converted.

**Comment by lsioctl** [comment] 2021-02-13 18:59
> 
> 
> Thanks for your kind words about the code.
> 
> The problem is that, in your scenario,
> 
> ```c++
> ini.sections["bitbucket.org"]["Usera"]
> ```
> 
> creates a new entry "Usera" in the "bitbucket.org" section using the default string constructor, thus resulting in an empty string, which then gets passed to the user variable. To handle missing entries and custom default values, you could use something like this: https://stackoverflow.com/a/2333816 I don't think you need the extract function in your example, as that's purely for convenient conversion from strings to other types.
> 
> Does this explain, and help you further?

Hello !

It explains a lot, thank you ! I am still a bit confused why the behavior seems different when I 'extract' an integer for example (using the other extract overload).

**Comment by lsioctl** [comment] 2021-02-13 19:01
> 
> 
> What do you think of this (just committed)?
> 
> ```c++
> template <typename CharT, typename T>
> inline bool get_value(const std::map<std::basic_string<CharT>, std::basic_string<CharT>> & sec, const std::basic_string<CharT> & key, T & dst) {
> 	const auto it = sec.find(key);
> 	if (it == sec.end()) return false;
> 	return extract(it->second, dst);
> }
> ```
> 
> I think that function has the behaviour you wish. Example:
> 
> ```c++
> int a = 4;
> get_value(sec, std::string("a"), a);
> ```
> 
> Here, `a` will retain the value 4 if the key does not exist in the section `sec`, or if the value cannot be converted.

I think it is perfect ! I will use this one for getting my values. Thank you for your quick response !

**Comment by mcmtroffaes** [comment] 2021-02-13 23:46
Splendid, glad this is working for you.

**Closed as completed by mcmtroffaes** 2021-02-13 23:46 UTC
